Update openvscode-server release action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -51,7 +51,7 @@ jobs:
     env:
       OS_NAME: 'linux'
       VSCODE_ARCH: ${{ matrix.vscode_arch }}
-      NPM_REGISTRY: 'https://registry.yarnpkg.com'
+      NPM_REGISTRY: 'https://registry.npmjs.org'
     steps:
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
@@ -64,20 +64,17 @@ jobs:
           path: openvscode-server
           token: ${{ secrets.VSCODE_GITHUB_TOKEN }}
 
-      - uses: actions/setup-node@v3
+      - uses: actions/setup-node@v4
         with:
-          node-version: 20
-
-      - name: Install Yarn
-        run: npm install -g yarn
+          node-version-file: .nvmrc
 
       - name: Setup system services
         working-directory: ./openvscode-server
         run: |
           set -e
           # Start X server
-          sudo apt-get update
-          sudo apt-get install -y pkg-config \
+          ./build/azure-pipelines/linux/apt-retry.sh sudo apt-get update
+          ./build/azure-pipelines/linux/apt-retry.sh sudo apt-get install -y pkg-config \
             dbus \
             xvfb \
             libgtk-3-0 \
@@ -98,26 +95,26 @@ jobs:
         id: nodeModulesCacheKey
         run: |
           mkdir -p .build
-          echo "value=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js ${{ matrix.vscode_arch }})" >> $GITHUB_OUTPUT
+          echo "value=$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js linux ${{ matrix.vscode_arch }})" >> $GITHUB_OUTPUT
       - name: Cache node modules
         id: cacheNodeModules
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: "openvscode-server/**/node_modules"
           key: ${{ runner.os }}-cacheNodeModulesLinux-${{ steps.nodeModulesCacheKey.outputs.value }}
-      - name: Get yarn cache directory path
+      - name: Get npm cache directory path
         working-directory: ./openvscode-server
-        id: yarnCacheDirPath
+        id: npmCacheDirPath
         if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
-        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
-      - name: Cache yarn directory
+        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
+      - name: Cache npm directory
         if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
-          path: ${{ steps.yarnCacheDirPath.outputs.dir }}
-          key: ${{ runner.os }}-yarnCacheDir-${{ steps.nodeModulesCacheKey.outputs.value }}
-          restore-keys: ${{ runner.os }}-yarnCacheDir-
-      - name: Execute yarn
+          path: ${{ steps.npmCacheDirPath.outputs.dir }}
+          key: ${{ runner.os }}-npmCacheDir-${{ steps.nodeModulesCacheKey.outputs.value }}
+          restore-keys: ${{ runner.os }}-npmCacheDir-
+      - name: Execute npm
         working-directory: ./openvscode-server
         if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
         env:
@@ -129,28 +126,29 @@ jobs:
         run: |
           set -e
 
-          # To workaround the issue of yarn not respecting the registry value from .npmrc
-          yarn config set registry "$NPM_REGISTRY"
+          npm config set registry "$NPM_REGISTRY"
 
+          cd ./build
           for i in {1..5}; do # try 5 times
-            yarn --cwd build --frozen-lockfile --check-files && break
-            if [ $i -eq 3 ]; then
-              echo "Yarn failed too many times" >&2
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
               exit 1
             fi
-            echo "Yarn failed $i, trying again..."
+            echo "Npm install failed $i, trying again..."
           done
 
           export VSCODE_SYSROOT_PREFIX='-glibc-2.17'
           source ./build/azure-pipelines/linux/setup-env.sh --only-remote
 
+          cd ..
           for i in {1..5}; do # try 5 times
-            yarn --frozen-lockfile --check-files && break
-            if [ $i -eq 3 ]; then
-              echo "Yarn failed too many times" >&2
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
               exit 1
             fi
-            echo "Yarn failed $i, trying again..."
+            echo "Npm install failed $i, trying again..."
           done
 
       - name: Update product.json
@@ -186,7 +184,7 @@ jobs:
           echo "distro_commit: ${distro_commit}"
 
           VSCODE_DISTRO_COMMIT="${distro_commit}" \
-          yarn gulp vscode-reh-web-linux-${{ matrix.vscode_arch }}-min
+          npm run gulp vscode-reh-web-linux-${{ matrix.vscode_arch }}-min
         env:
           DISABLE_V8_COMPILE_CACHE: 1
 
@@ -194,32 +192,40 @@ jobs:
         if: matrix.vscode_arch == 'x64'
         working-directory: ./openvscode-server
         run: |
-          yarn playwright-install
+          npm run playwright-install
 
       - name: Build integration tests
         if: matrix.vscode_arch == 'x64'
         working-directory: ./openvscode-server
         run: |
           set -e
-          yarn gulp \
+          npm run gulp \
             compile-extension:configuration-editing \
-            compile-extension:vscode-api-tests \
-            compile-extension:markdown-language-features \
-            compile-extension:typescript-language-features \
+            compile-extension:css-language-features-server \
             compile-extension:emmet \
             compile-extension:git \
+            compile-extension:github-authentication \
+            compile-extension:html-language-features-server \
             compile-extension:ipynb \
-            compile-extension-media
-        env:
-          DISABLE_V8_COMPILE_CACHE: 1
+            compile-extension:notebook-renderers \
+            compile-extension:json-language-features-server \
+            compile-extension:markdown-language-features \
+            compile-extension-media \
+            compile-extension:microsoft-authentication \
+            compile-extension:typescript-language-features \
+            compile-extension:vscode-api-tests \
+            compile-extension:vscode-colorize-tests \
+            compile-extension:vscode-test-resolver
 
-      - name: Compile test suites
+      - name: Compile Integration Tests
         if: matrix.vscode_arch == 'x64'
-        working-directory: ./openvscode-server
-        run: |
-          set -e
-          yarn --cwd test/smoke compile
-          yarn --cwd test/integration/browser compile
+        working-directory: ./openvscode-server/test/integration/browser
+        run: npm run compile
+
+      - name: Compile Smoke Tests
+        if: matrix.vscode_arch == 'x64'
+        working-directory: ./openvscode-server/test/smoke
+        run: npm run compile
 
       - name: Run integration tests
         if: matrix.vscode_arch == 'x64'
@@ -235,7 +241,7 @@ jobs:
         run: |
           set -e
           VSCODE_REMOTE_SERVER_PATH="$GITHUB_WORKSPACE/vscode-reh-web-linux-${{ matrix.vscode_arch }}" \
-          yarn smoketest-no-compile --web --headless --electronArgs="--disable-dev-shm-usage"
+          npm run smoketest-no-compile -- --web --tracing --headless --electronArgs="--disable-dev-shm-usage"
 
       - name: Bundle tarfile
         id: bundle_tar
