Update release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,54 +26,49 @@ env:
   RELEASE_COMMIT: ${{ github.event.inputs.commit || 'main' }}
 
 jobs:
-  build-dependencies:
-    runs-on: ubuntu-latest
-    container:
-      image: ${{ matrix.image }}
-    strategy:
-      fail-fast: true
-      matrix:
-        include:
-        - vscode_arch: x64
-          npm_arch: x64
-          image: gitpod/openvscode-server-linux-build-agent:centos7-devtoolset8-x64
-        # - vscode_arch: arm64
-        #   npm_arch: arm64
-        #   image: gitpod/openvscode-server-linux-build-agent:centos7-devtoolset8-arm64
+  # build-dependencies:
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: ${{ matrix.image }}
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       include:
+  #       - vscode_arch: x64
+  #         npm_arch: x64
+  #         image: gitpod/openvscode-server-linux-build-agent:centos7-devtoolset8-x64
+  #       # - vscode_arch: arm64
+  #       #   npm_arch: arm64
+  #       #   image: gitpod/openvscode-server-linux-build-agent:centos7-devtoolset8-arm64
 
-    name: Build native dependencies linux
-    if: github.event.inputs.commit || github.event.workflow_run.conclusion == 'success'
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          repository: ${{ github.repository_owner }}/openvscode-server
-          ref: ${{ env.RELEASE_COMMIT }}
-          token: ${{ secrets.VSCODE_GITHUB_TOKEN }}
+  #   name: Build native dependencies linux
+  #   if: github.event.inputs.commit || github.event.workflow_run.conclusion == 'success'
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         repository: ${{ github.repository_owner }}/openvscode-server
+  #         ref: ${{ env.RELEASE_COMMIT }}
+  #         token: ${{ secrets.VSCODE_GITHUB_TOKEN }}
 
-      - name: Execute yarn
-        run: |
-          set -e
-          export npm_config_arch=${{ matrix.npm_arch }}
-          yarn --cwd remote --frozen-lockfile --network-timeout 180000
+  #     - name: Execute yarn
+  #       run: |
+  #         set -e
+  #         export npm_config_arch=${{ matrix.npm_arch }}
+  #         yarn --cwd remote --frozen-lockfile --network-timeout 180000
 
-      - name: Compress node_modules output
-        run: |
-          set -e
-          tar -cz --ignore-failed-read -f reh_node_modules-${{ matrix.vscode_arch }}.tar.gz -C ./remote node_modules
+  #     - name: Compress node_modules output
+  #       run: |
+  #         set -e
+  #         tar -cz --ignore-failed-read -f reh_node_modules-${{ matrix.vscode_arch }}.tar.gz -C ./remote node_modules
 
-      - name: Upload compiled dependencies
-        uses: actions/upload-artifact@v3
-        with:
-          name: reh_node_modules-${{ matrix.vscode_arch }}
-          path: reh_node_modules-${{ matrix.vscode_arch }}.tar.gz
+  #     - name: Upload compiled dependencies
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: reh_node_modules-${{ matrix.vscode_arch }}
+  #         path: reh_node_modules-${{ matrix.vscode_arch }}.tar.gz
 
   build:
     runs-on: ubuntu-latest
-    container:
-      image: ${{ matrix.image }}
-      env:
-        OS_NAME: 'linux'
-        VSCODE_ARCH: ${{ matrix.vscode_arch }}
 
     # support only linux for now
     strategy:
@@ -82,13 +77,13 @@ jobs:
         include:
         - vscode_arch: x64
           npm_arch: x64
-          image: gitpod/openvscode-server-linux-build-agent:bionic-x64
+          deps_container: gitpod/openvscode-server-linux-build-agent:centos7-devtoolset8-x64
         - vscode_arch: arm64
           npm_arch: arm64
-          image: gitpod/openvscode-server-linux-build-agent:bionic-arm64
+          deps_container: gitpod/openvscode-server-linux-build-agent:centos7-devtoolset8-arm64
         - vscode_arch: armhf
           npm_arch: arm
-          image: gitpod/openvscode-server-linux-build-agent:bionic-armhf
+          deps_container: 
 
     name: Build linux-${{ matrix.vscode_arch }}
     needs: build-dependencies
@@ -96,7 +91,14 @@ jobs:
       release_commit: ${{ steps.bundle_tar.outputs.release_commit }}
       version: ${{ steps.bundle_tar.outputs.version }}
       quality: ${{ steps.bundle_tar.outputs.quality }}
+    env:
+      OS_NAME: 'linux'
+      VSCODE_ARCH: ${{ matrix.vscode_arch }}
+      NPM_REGISTRY: 'https://registry.yarnpkg.com'
     steps:
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
       - uses: actions/checkout@v3
         with:
           repository: ${{ github.repository_owner }}/openvscode-server
@@ -140,25 +142,40 @@ jobs:
         env:
           PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+          VSCODE_SKIP_NODE_VERSION_CHECK: 1
+          npm_config_arch: ${{ matrix.npm_arch }}
+          VSCODE_REMOTE_DEPENDENCIES_CONTAINER_NAME: ${{ matrix.deps_container }}
+          VSCODE_HOST_MOUNT: ${{ github.workspace }}/openvscode-server
         run: |
           set -e
-          export npm_config_arch=${{ matrix.npm_arch }}
-          yarn --frozen-lockfile --network-timeout 180000
 
-      - name: Download server build dependencies
-        if: matrix.vscode_arch == 'x64'
-        uses: actions/download-artifact@v3
-        with:
-          name: reh_node_modules-x64
-          path: ./openvscode-server
+          yarn --cwd build --frozen-lockfile --check-files
 
-      - name: Extract server node_modules output
-        if: matrix.vscode_arch == 'x64'
-        working-directory: ./openvscode-server
-        run: |
-          set -e
-          rm -rf remote/node_modules
-          tar -xzf reh_node_modules-x64.tar.gz --directory ./remote
+          docker run -e npm_config_arch -e NPM_REGISTRY \
+            -e VSCODE_REMOTE_DEPENDENCIES_CONTAINER_NAME -e VSCODE_HOST_MOUNT \
+            -e ELECTRON_SKIP_BINARY_DOWNLOAD -e PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD \
+            -e VSCODE_SKIP_NODE_VERSION_CHECK \
+            -v $GITHUB_WORKSPACE/openvscode-server:/home/builduser/openvscode-server \
+            -v /var/run/docker.sock:/var/run/docker.sock \
+            -w /home/builduser/openvscode-server gitpod/openvscode-server-linux-build-agent:bionic-$VSCODE_ARCH \
+            /bin/bash -c "./build/azure-pipelines/linux/install.sh"
+
+          sudo chown -R $USER:$USER $GITHUB_WORKSPACE/openvscode-server
+
+      # - name: Download server build dependencies
+      #   if: matrix.vscode_arch == 'x64'
+      #   uses: actions/download-artifact@v3
+      #   with:
+      #     name: reh_node_modules-x64
+      #     path: ./openvscode-server
+
+      # - name: Extract server node_modules output
+      #   if: matrix.vscode_arch == 'x64'
+      #   working-directory: ./openvscode-server
+      #   run: |
+      #     set -e
+      #     rm -rf remote/node_modules
+      #     tar -xzf reh_node_modules-x64.tar.gz --directory ./remote
 
       - name: Update product.json
         working-directory: ./openvscode-server
